# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feeduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='feeduser',
            name='password',
        ),
        migrations.AddField(
            model_name='feeduser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
